#!/usr/bin/env bash
# Vendors the card contract files from PickMe into MoneyTalks/contracts/ and
# regenerates MANIFEST.json (sha256 per file) so the drift-check test can
# detect a stale copy.
#
# Two source modes:
#   scripts/sync-contracts.sh                    # local sibling checkout (default, offline)
#   scripts/sync-contracts.sh /path/to/contracts  # local, explicit path
#   scripts/sync-contracts.sh --ref <git-ref>     # remote: PickMe's public raw URLs at <git-ref>
#
# MANIFEST.json gets a second party this script alone cannot fake: an
# `_upstream` block recording the PickMe ref + commit synced from, and the
# sha256 of each file as PickMe had it (the SOURCE bytes) — not the
# destination bytes sync-contracts.sh just wrote. Before this, the manifest
# was regenerated by hashing the files this script had just copied, so it
# could only ever describe the local vendored copy: it detected hand-edits to
# MoneyTalks/contracts/ but could never detect that PickMe's canonical files
# had moved on, because nothing recorded what PickMe last had. See
# docs/superpowers/specs/2026-08-18-annual-fee-renewal-calendar-design.md §12.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DEST="$REPO_ROOT/contracts"
UPSTREAM_REPO="https://github.com/zubairmuwwakil/PickMe"

MODE="local"
REF=""
LOCAL_SOURCE=""

while [ $# -gt 0 ]; do
  case "$1" in
    --ref)
      MODE="remote"
      REF="${2:-}"
      if [ -z "$REF" ]; then
        echo "sync-contracts: --ref requires a git ref (branch, tag, or sha)" >&2
        exit 1
      fi
      shift 2
      ;;
    --ref=*)
      MODE="remote"
      REF="${1#--ref=}"
      shift
      ;;
    -h|--help)
      sed -n '2,13p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      LOCAL_SOURCE="$1"
      shift
      ;;
  esac
done

# Relative to the source root / $DEST. Keep in sync with the expected file
# list in src/lib/contracts/contracts.test.ts.
FILES=(
  "card-catalogue.json"
  "benefits-catalogue.json"
  "engine-fixtures.json"
  "schema/card-catalogue.schema.json"
  "schema/benefits-catalogue.schema.json"
  "schema/engine-fixtures.schema.json"
)

sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

mkdir -p "$DEST/schema"

declare -a SOURCE_SHAS

if [ "$MODE" = "remote" ]; then
  echo "sync-contracts: fetching from $UPSTREAM_REPO @ $REF (remote mode)"

  RAW_BASE="https://raw.githubusercontent.com/zubairmuwwakil/PickMe/$REF/contracts"
  TMP_DIR="$(mktemp -d)"
  trap 'rm -rf "$TMP_DIR"' EXIT

  for f in "${FILES[@]}"; do
    mkdir -p "$TMP_DIR/$(dirname "$f")"
    url="$RAW_BASE/$f"
    if ! curl -fsSL "$url" -o "$TMP_DIR/$f"; then
      echo "sync-contracts: failed to fetch $url" >&2
      exit 1
    fi
  done

  # Resolve the ref to a full commit sha via the GitHub API — a branch name
  # like "main" is not itself a stable record of what was synced.
  api_response="$(curl -fsSL \
    -H "Accept: application/vnd.github+json" \
    "https://api.github.com/repos/zubairmuwwakil/PickMe/commits/$REF")" \
    || { echo "sync-contracts: failed to resolve commit sha for ref '$REF' via GitHub API" >&2; exit 1; }
  UPSTREAM_COMMIT="$(printf '%s' "$api_response" | node -e '
    let data = "";
    process.stdin.on("data", (chunk) => (data += chunk));
    process.stdin.on("end", () => {
      const parsed = JSON.parse(data);
      if (!parsed.sha) { process.exit(1); }
      process.stdout.write(parsed.sha);
    });
  ')"
  if [ -z "$UPSTREAM_COMMIT" ]; then
    echo "sync-contracts: GitHub API response for ref '$REF' had no sha" >&2
    exit 1
  fi
  UPSTREAM_REF="$REF"

  for f in "${FILES[@]}"; do
    hash=$(sha256_of "$TMP_DIR/$f")
    SOURCE_SHAS+=("$hash")
    cp "$TMP_DIR/$f" "$DEST/$f"
  done
else
  SOURCE="${LOCAL_SOURCE:-$REPO_ROOT/../PickMe/contracts}"
  if [ ! -d "$SOURCE" ]; then
    echo "sync-contracts: source directory not found: $SOURCE" >&2
    exit 1
  fi
  echo "sync-contracts: copying from local sibling checkout $SOURCE"

  PICKME_ROOT="$(cd "$SOURCE/.." && pwd)"
  if git -C "$PICKME_ROOT" rev-parse HEAD >/dev/null 2>&1; then
    UPSTREAM_COMMIT="$(git -C "$PICKME_ROOT" rev-parse HEAD)"
    UPSTREAM_REF="$(git -C "$PICKME_ROOT" rev-parse --abbrev-ref HEAD)"
  else
    echo "sync-contracts: warning: $PICKME_ROOT is not a git checkout — _upstream.commit/.ref will be \"unknown\"" >&2
    UPSTREAM_COMMIT="unknown"
    UPSTREAM_REF="unknown"
  fi

  for f in "${FILES[@]}"; do
    src="$SOURCE/$f"
    if [ ! -f "$src" ]; then
      echo "sync-contracts: missing source file: $src" >&2
      exit 1
    fi
    hash=$(sha256_of "$src")
    SOURCE_SHAS+=("$hash")
    cp "$src" "$DEST/$f"
  done
fi

manifest="$DEST/MANIFEST.json"
tmp_manifest="$manifest.tmp"
{
  echo "{"
  echo "  \"_upstream\": {"
  printf '    "repo": "%s",\n' "$UPSTREAM_REPO"
  printf '    "ref": "%s",\n' "$UPSTREAM_REF"
  printf '    "commit": "%s",\n' "$UPSTREAM_COMMIT"
  echo "    \"files\": {"
  last_index=$((${#FILES[@]} - 1))
  for i in "${!FILES[@]}"; do
    f="${FILES[$i]}"
    if [ "$i" -eq "$last_index" ]; then
      printf '      "%s": "%s"\n' "$f" "${SOURCE_SHAS[$i]}"
    else
      printf '      "%s": "%s",\n' "$f" "${SOURCE_SHAS[$i]}"
    fi
  done
  echo "    }"
  echo "  },"
  for i in "${!FILES[@]}"; do
    f="${FILES[$i]}"
    hash=$(sha256_of "$DEST/$f")
    printf '  "%s": "%s",\n' "$f" "$hash"
  done | sed '$ s/,$//'
  echo "}"
} > "$tmp_manifest"
mv "$tmp_manifest" "$manifest"

echo "sync-contracts: synced ${#FILES[@]} files from ${UPSTREAM_REF:-local} (upstream commit ${UPSTREAM_COMMIT:-unknown})"
