import type { CardFormValues } from "@/components/card-form";
import type { Network, SpendCategory } from "./types";

export type CardTheme =
  | "cobalt"
  | "platinum"
  | "scotia-red"
  | "scotia-gold"
  | "td-green"
  | "rbc-blue"
  | "cibc-maroon"
  | "bmo-blue"
  | "rogers-red"
  | "tangerine-orange"
  | "wealthsimple-black"
  | "triangle-red"
  | "crypto-indigo"
  | "marriott"
  | "mbna"
  | "national-bank"
  | "pc-optimum"
  | "amazon"
  | "westjet"
  | "default";

export interface PointValuationOption {
  label: string;
  value: string;
  description: string;
}

export interface CardPreset {
  id: string;
  name: string;
  issuer: string;
  network: Network;
  annualFee: number;
  theme: CardTheme;
  programName?: string;
  highlights: string[];
  pointValuationOptions?: PointValuationOption[];
  values: CardFormValues;
}

export const CARD_PRESETS: CardPreset[] = [
  // --- AMERICAN EXPRESS ---
  {
    id: "amex-cobalt",
    name: "American Express Cobalt Card",
    issuer: "American Express",
    network: "AMEX",
    annualFee: 191.88,
    theme: "cobalt",
    programName: "Amex Membership Rewards",
    highlights: ["5x Groceries & Dining ($2.5k/mo cap)", "3x Streaming", "2x Gas & Transit", "1x Base"],
    pointValuationOptions: [
      { label: "1.00¢ (Statement credit / base)", value: "1", description: "Direct cashback on charges" },
      { label: "1.50¢ (Conservative travel)", value: "1.5", description: "Fixed points travel or partner transfer" },
      { label: "2.00¢ (Aeroplan / Max transfer)", value: "2", description: "Optimal 1:1 transfer to Aeroplan" },
    ],
    values: {
      nickname: "Amex Cobalt",
      issuer: "American Express",
      network: "AMEX",
      lastFour: "",
      country: "CA",
      currency: "CAD",
      limit: "",
      statementDay: "",
      dueDay: "",
      aprPct: "20.99",
      annualFee: "191.88",
      feeMonthDay: "",
      feeCancelGraceDays: "30",
      rewards: {
        pointValueCents: "1",
        fxFeePct: "2.5",
        baseMultiplier: "1",
        capGroups: [
          {
            id: "cobalt-eats-cap",
            label: "5x Eats & drinks ($2,500/month)",
            cap: "2500",
            capWindow: "MONTH",
          },
        ],
        categoryRates: [
          { category: "groceries", multiplier: "5", cap: "", capWindow: "MONTH", capGroupId: "cobalt-eats-cap", requiresConditionId: "" },
          { category: "dining", multiplier: "5", cap: "", capWindow: "MONTH", capGroupId: "cobalt-eats-cap", requiresConditionId: "" },
          { category: "streaming", multiplier: "3", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
          { category: "gas", multiplier: "2", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
          { category: "travel", multiplier: "2", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
        ],
        credits: [],
        conditions: [],
        merchantRates: [],
        baseRateOverrides: [],
      },
    },
  },
  {
    id: "amex-platinum",
    name: "The Platinum Card from American Express",
    issuer: "American Express",
    network: "AMEX",
    annualFee: 799,
    theme: "platinum",
    programName: "Amex Membership Rewards",
    highlights: ["2x Dining & Travel", "$200 Annual Travel Credit", "$200 Annual Dining Credit", "Unlimited Lounge Access"],
    pointValuationOptions: [
      { label: "1.00¢ (Statement credit)", value: "1", description: "Standard 1:1 statement credit" },
      { label: "1.50¢ (Travel)", value: "1.5", description: "Fixed points travel redemption" },
      { label: "2.00¢ (Aeroplan transfer)", value: "2", description: "High-value partner redemption" },
    ],
    values: {
      nickname: "Amex Platinum",
      issuer: "American Express",
      network: "AMEX",
      lastFour: "",
      country: "CA",
      currency: "CAD",
      limit: "",
      statementDay: "",
      dueDay: "",
      aprPct: "20.99",
      annualFee: "799.00",
      feeMonthDay: "",
      feeCancelGraceDays: "30",
      rewards: {
        pointValueCents: "1",
        fxFeePct: "2.5",
        baseMultiplier: "1",
        capGroups: [],
        categoryRates: [
          { category: "dining", multiplier: "2", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
          { category: "travel", multiplier: "2", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
          { category: "hotel", multiplier: "2", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
        ],
        credits: [
          { id: "plat-travel-credit", label: "Annual travel credit", value: "200.00", period: "YEAR" },
          { id: "plat-dining-credit", label: "Annual dining credit", value: "200.00", period: "YEAR" },
        ],
        conditions: [],
        merchantRates: [],
        baseRateOverrides: [],
      },
    },
  },
  {
    id: "amex-bonvoy",
    name: "Marriott Bonvoy American Express Card",
    issuer: "American Express",
    network: "AMEX",
    annualFee: 120,
    theme: "marriott",
    programName: "Marriott Bonvoy",
    highlights: ["5x Marriott Purchases", "2x Base on everything", "Annual Free Night Award (up to 35,000 pts)", "Silver Elite Status"],
    pointValuationOptions: [
      { label: "0.80¢ (Standard hotel value)", value: "0.8", description: "Marriott Bonvoy reward night redemption" },
      { label: "1.00¢ (High-season booking)", value: "1", description: "Peak hotel stay valuation" },
    ],
    values: {
      nickname: "Amex Marriott Bonvoy",
      issuer: "American Express",
      network: "AMEX",
      lastFour: "",
      country: "CA",
      currency: "CAD",
      limit: "",
      statementDay: "",
      dueDay: "",
      aprPct: "20.99",
      annualFee: "120.00",
      feeMonthDay: "",
      feeCancelGraceDays: "30",
      rewards: {
        pointValueCents: "0.8",
        fxFeePct: "2.5",
        baseMultiplier: "2",
        capGroups: [],
        categoryRates: [
          { category: "hotel", multiplier: "5", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
        ],
        credits: [],
        conditions: [],
        merchantRates: [
          { id: "marriott-direct-stay", merchant: "Marriott Bonvoy Hotels & Resorts", multiplier: "5", requiresConditionId: "" },
        ],
        baseRateOverrides: [],
      },
    },
  },
  {
    id: "simplycash-amex",
    name: "SimplyCash Card from American Express",
    issuer: "American Express",
    network: "AMEX",
    annualFee: 0,
    theme: "cobalt",
    programName: "Cashback",
    highlights: ["2% Gas & Groceries ($15k annual cap each)", "1.25% Base on everything else", "$0 Annual Fee"],
    pointValuationOptions: [{ label: "1.00¢ (Cashback)", value: "1", description: "Direct CAD cash back statement credit" }],
    values: {
      nickname: "Amex SimplyCash",
      issuer: "American Express",
      network: "AMEX",
      lastFour: "",
      country: "CA",
      currency: "CAD",
      limit: "",
      statementDay: "",
      dueDay: "",
      aprPct: "20.99",
      annualFee: "0.00",
      feeMonthDay: "",
      feeCancelGraceDays: "30",
      rewards: {
        pointValueCents: "1",
        fxFeePct: "2.5",
        baseMultiplier: "1.25",
        capGroups: [],
        categoryRates: [
          { category: "gas", multiplier: "2", cap: "15000", capWindow: "YEAR", capGroupId: "", requiresConditionId: "" },
          { category: "groceries", multiplier: "2", cap: "15000", capWindow: "YEAR", capGroupId: "", requiresConditionId: "" },
        ],
        credits: [],
        conditions: [],
        merchantRates: [],
        baseRateOverrides: [],
      },
    },
  },

  // --- SCOTIABANK ---
  {
    id: "scotia-gold-amex",
    name: "Scotiabank Gold American Express Card",
    issuer: "Scotiabank",
    network: "AMEX",
    annualFee: 120,
    theme: "scotia-gold",
    programName: "Scene+",
    highlights: ["5x Groceries, Dining & Entertainment", "3x Gas, Transit & Streaming", "0% FX Fee (No Foreign Fees)", "Scene+ Points"],
    pointValuationOptions: [
      { label: "1.00¢ (Scene+ Standard)", value: "1", description: "1,000 Scene+ points = $10.00 travel/groceries" },
    ],
    values: {
      nickname: "Scotiabank Gold Amex",
      issuer: "Scotiabank",
      network: "AMEX",
      lastFour: "",
      country: "CA",
      currency: "CAD",
      limit: "",
      statementDay: "",
      dueDay: "",
      aprPct: "20.99",
      annualFee: "120.00",
      feeMonthDay: "",
      feeCancelGraceDays: "30",
      rewards: {
        pointValueCents: "1",
        fxFeePct: "0",
        baseMultiplier: "1",
        capGroups: [
          {
            id: "scotia-gold-accelerated",
            label: "5x/3x Accelerated Spend ($50,000/year)",
            cap: "50000",
            capWindow: "YEAR",
          },
        ],
        categoryRates: [
          { category: "groceries", multiplier: "5", cap: "", capWindow: "YEAR", capGroupId: "scotia-gold-accelerated", requiresConditionId: "" },
          { category: "dining", multiplier: "5", cap: "", capWindow: "YEAR", capGroupId: "scotia-gold-accelerated", requiresConditionId: "" },
          { category: "gas", multiplier: "3", cap: "", capWindow: "YEAR", capGroupId: "scotia-gold-accelerated", requiresConditionId: "" },
          { category: "streaming", multiplier: "3", cap: "", capWindow: "YEAR", capGroupId: "scotia-gold-accelerated", requiresConditionId: "" },
          { category: "travel", multiplier: "3", cap: "", capWindow: "YEAR", capGroupId: "scotia-gold-accelerated", requiresConditionId: "" },
        ],
        credits: [],
        conditions: [
          {
            id: "scotia-ultimate-waiver",
            label: "Scotia Ultimate Banking package active (fee waiver)",
            enabled: false,
            annualFeeReduction: "120.00",
          },
        ],
        merchantRates: [
          { id: "empire-sobeys-6x", merchant: "Sobeys / FreshCo / IGA / Foodland / Voila", multiplier: "6", requiresConditionId: "" },
        ],
        baseRateOverrides: [],
      },
    },
  },
  {
    id: "scotia-momentum-vi",
    name: "Scotia Momentum Visa Infinite + Card",
    issuer: "Scotiabank",
    network: "VISA",
    annualFee: 120,
    theme: "scotia-red",
    programName: "Cashback",
    highlights: ["4% Groceries & Recurring Bills", "2% Gas & Transit", "1% Base", "$25k Annual Cap"],
    pointValuationOptions: [{ label: "1.00¢ (Cashback)", value: "1", description: "Direct CAD cashback" }],
    values: {
      nickname: "Scotia Momentum Visa Infinite",
      issuer: "Scotiabank",
      network: "VISA",
      lastFour: "",
      country: "CA",
      currency: "CAD",
      limit: "",
      statementDay: "",
      dueDay: "",
      aprPct: "20.99",
      annualFee: "120.00",
      feeMonthDay: "",
      feeCancelGraceDays: "30",
      rewards: {
        pointValueCents: "1",
        fxFeePct: "2.5",
        baseMultiplier: "1",
        capGroups: [
          {
            id: "scotia-momentum-4pct-cap",
            label: "4% Groceries & Recurring Bills ($25,000/year)",
            cap: "25000",
            capWindow: "YEAR",
          },
          {
            id: "scotia-momentum-2pct-cap",
            label: "2% Gas & Transit ($25,000/year)",
            cap: "25000",
            capWindow: "YEAR",
          },
        ],
        categoryRates: [
          { category: "groceries", multiplier: "4", cap: "", capWindow: "YEAR", capGroupId: "scotia-momentum-4pct-cap", requiresConditionId: "" },
          { category: "bills", multiplier: "4", cap: "", capWindow: "YEAR", capGroupId: "scotia-momentum-4pct-cap", requiresConditionId: "" },
          { category: "gas", multiplier: "2", cap: "", capWindow: "YEAR", capGroupId: "scotia-momentum-2pct-cap", requiresConditionId: "" },
          { category: "dining", multiplier: "2", cap: "", capWindow: "YEAR", capGroupId: "scotia-momentum-2pct-cap", requiresConditionId: "" },
        ],
        credits: [],
        conditions: [
          {
            id: "scotia-ultimate-momentum-waiver",
            label: "Scotia Ultimate Banking package active (fee waiver)",
            enabled: false,
            annualFeeReduction: "120.00",
          },
        ],
        merchantRates: [],
        baseRateOverrides: [],
      },
    },
  },
  {
    id: "scotia-passport-vi",
    name: "Scotiabank Passport Visa Infinite + Card",
    issuer: "Scotiabank",
    network: "VISA",
    annualFee: 150,
    theme: "scotia-red",
    programName: "Scene+",
    highlights: ["0% FX Fee (No Foreign Fees)", "3x Groceries, Dining & Entertainment", "2x Transit & Gas", "6 Free Lounge Passes/year"],
    pointValuationOptions: [{ label: "1.00¢ (Scene+ Standard)", value: "1", description: "1,000 Scene+ = $10.00 travel/grocery" }],
    values: {
      nickname: "Scotiabank Passport Visa Infinite",
      issuer: "Scotiabank",
      network: "VISA",
      lastFour: "",
      country: "CA",
      currency: "CAD",
      limit: "",
      statementDay: "",
      dueDay: "",
      aprPct: "20.99",
      annualFee: "150.00",
      feeMonthDay: "",
      feeCancelGraceDays: "30",
      rewards: {
        pointValueCents: "1",
        fxFeePct: "0",
        baseMultiplier: "1",
        capGroups: [
          {
            id: "scotia-passport-cap",
            label: "Accelerated spend ($50,000/year)",
            cap: "50000",
            capWindow: "YEAR",
          },
        ],
        categoryRates: [
          { category: "groceries", multiplier: "3", cap: "", capWindow: "YEAR", capGroupId: "scotia-passport-cap", requiresConditionId: "" },
          { category: "dining", multiplier: "3", cap: "", capWindow: "YEAR", capGroupId: "scotia-passport-cap", requiresConditionId: "" },
          { category: "gas", multiplier: "2", cap: "", capWindow: "YEAR", capGroupId: "scotia-passport-cap", requiresConditionId: "" },
          { category: "travel", multiplier: "2", cap: "", capWindow: "YEAR", capGroupId: "scotia-passport-cap", requiresConditionId: "" },
        ],
        credits: [],
        conditions: [
          {
            id: "scotia-ultimate-passport-waiver",
            label: "Scotia Ultimate Banking package active (fee waiver)",
            enabled: false,
            annualFeeReduction: "150.00",
          },
        ],
        merchantRates: [],
        baseRateOverrides: [],
      },
    },
  },

  // --- TD CANADA TRUST ---
  {
    id: "td-aeroplan-vi",
    name: "TD Aeroplan Visa Infinite Card",
    issuer: "TD",
    network: "VISA",
    annualFee: 139,
    theme: "td-green",
    programName: "Air Canada Aeroplan",
    highlights: ["1.5x Groceries, Gas & Air Canada", "1x Base", "Free First Checked Bag on Air Canada", "NEXUS Rebate"],
    pointValuationOptions: [
      { label: "1.50¢ (Conservative flight value)", value: "1.5", description: "Standard economy flight redemption" },
      { label: "1.80¢ (Average Aeroplan valuation)", value: "1.8", description: "Target Aeroplan baseline value" },
      { label: "2.10¢ (Business / Partner flights)", value: "2.1", description: "Premium cabin partner redemption" },
    ],
    values: {
      nickname: "TD Aeroplan Visa Infinite",
      issuer: "TD",
      network: "VISA",
      lastFour: "",
      country: "CA",
      currency: "CAD",
      limit: "",
      statementDay: "",
      dueDay: "",
      aprPct: "20.99",
      annualFee: "139.00",
      feeMonthDay: "",
      feeCancelGraceDays: "30",
      rewards: {
        pointValueCents: "1.8",
        fxFeePct: "2.5",
        baseMultiplier: "1",
        capGroups: [
          {
            id: "td-aeroplan-cap",
            label: "1.5x Accelerated Spend ($80,000/year)",
            cap: "80000",
            capWindow: "YEAR",
          },
        ],
        categoryRates: [
          { category: "groceries", multiplier: "1.5", cap: "", capWindow: "YEAR", capGroupId: "td-aeroplan-cap", requiresConditionId: "" },
          { category: "gas", multiplier: "1.5", cap: "", capWindow: "YEAR", capGroupId: "td-aeroplan-cap", requiresConditionId: "" },
          { category: "travel", multiplier: "1.5", cap: "", capWindow: "YEAR", capGroupId: "td-aeroplan-cap", requiresConditionId: "" },
        ],
        credits: [],
        conditions: [
          {
            id: "td-all-inclusive-waiver",
            label: "TD All-Inclusive Banking Plan active (fee waiver)",
            enabled: false,
            annualFeeReduction: "139.00",
          },
        ],
        merchantRates: [
          { id: "td-air-canada-direct", merchant: "Air Canada / Vacations", multiplier: "1.5", requiresConditionId: "" },
        ],
        baseRateOverrides: [],
      },
    },
  },
  {
    id: "td-first-class-travel-vi",
    name: "TD First Class Travel Visa Infinite Card",
    issuer: "TD",
    network: "VISA",
    annualFee: 139,
    theme: "td-green",
    programName: "TD Rewards",
    highlights: ["8x Expedia For TD", "6x Groceries & Dining", "4x Recurring Bills & Streaming", "2x Base on everything"],
    pointValuationOptions: [
      { label: "0.50¢ (Expedia For TD / Travel)", value: "0.5", description: "200 TD points = $1.00 Expedia For TD booking" },
      { label: "0.25¢ (Statement credit)", value: "0.25", description: "400 TD points = $1.00 cash" },
    ],
    values: {
      nickname: "TD First Class Travel VI",
      issuer: "TD",
      network: "VISA",
      lastFour: "",
      country: "CA",
      currency: "CAD",
      limit: "",
      statementDay: "",
      dueDay: "",
      aprPct: "20.99",
      annualFee: "139.00",
      feeMonthDay: "",
      feeCancelGraceDays: "30",
      rewards: {
        pointValueCents: "0.5",
        fxFeePct: "2.5",
        baseMultiplier: "2",
        capGroups: [],
        categoryRates: [
          { category: "groceries", multiplier: "6", cap: "25000", capWindow: "YEAR", capGroupId: "", requiresConditionId: "" },
          { category: "dining", multiplier: "6", cap: "25000", capWindow: "YEAR", capGroupId: "", requiresConditionId: "" },
          { category: "bills", multiplier: "4", cap: "25000", capWindow: "YEAR", capGroupId: "", requiresConditionId: "" },
          { category: "streaming", multiplier: "4", cap: "25000", capWindow: "YEAR", capGroupId: "", requiresConditionId: "" },
        ],
        credits: [
          { id: "td-expedia-credit", label: "$100 Annual Expedia For TD travel credit", value: "100.00", period: "YEAR" },
        ],
        conditions: [
          {
            id: "td-fct-all-inclusive-waiver",
            label: "TD All-Inclusive Banking Plan active (fee waiver)",
            enabled: false,
            annualFeeReduction: "139.00",
          },
        ],
        merchantRates: [
          { id: "expedia-for-td-8x", merchant: "Expedia For TD", multiplier: "8", requiresConditionId: "" },
        ],
        baseRateOverrides: [],
      },
    },
  },
  {
    id: "td-cash-back-vi",
    name: "TD Cash Back Visa Infinite Card",
    issuer: "TD",
    network: "VISA",
    annualFee: 139,
    theme: "td-green",
    programName: "Cashback",
    highlights: ["3% Groceries, Gas & Recurring Bills ($15k cap each)", "1% Base", "Free Deluxe TD Auto Club Roadside Assistance"],
    pointValuationOptions: [{ label: "1.00¢ (Cashback)", value: "1", description: "Direct CAD cash back redemption" }],
    values: {
      nickname: "TD Cash Back Visa Infinite",
      issuer: "TD",
      network: "VISA",
      lastFour: "",
      country: "CA",
      currency: "CAD",
      limit: "",
      statementDay: "",
      dueDay: "",
      aprPct: "20.99",
      annualFee: "139.00",
      feeMonthDay: "",
      feeCancelGraceDays: "30",
      rewards: {
        pointValueCents: "1",
        fxFeePct: "2.5",
        baseMultiplier: "1",
        capGroups: [],
        categoryRates: [
          { category: "groceries", multiplier: "3", cap: "15000", capWindow: "YEAR", capGroupId: "", requiresConditionId: "" },
          { category: "gas", multiplier: "3", cap: "15000", capWindow: "YEAR", capGroupId: "", requiresConditionId: "" },
          { category: "bills", multiplier: "3", cap: "15000", capWindow: "YEAR", capGroupId: "", requiresConditionId: "" },
        ],
        credits: [],
        conditions: [
          {
            id: "td-cb-all-inclusive-waiver",
            label: "TD All-Inclusive Banking Plan active (fee waiver)",
            enabled: false,
            annualFeeReduction: "139.00",
          },
        ],
        merchantRates: [],
        baseRateOverrides: [],
      },
    },
  },

  // --- RBC ROYAL BANK ---
  {
    id: "rbc-avion-vi",
    name: "RBC Avion Visa Infinite",
    issuer: "RBC",
    network: "VISA",
    annualFee: 120,
    theme: "rbc-blue",
    programName: "RBC Avion Rewards",
    highlights: ["1.25x Travel Purchases", "1x Base", "Avion Air Redemption Chart", "Premium Travel Insurance"],
    pointValuationOptions: [
      { label: "1.00¢ (Standard redemption)", value: "1", description: "Direct travel or gift card booking" },
      { label: "1.50¢ (Flight redemption chart)", value: "1.5", description: "RBC Avion fixed flight redemption schedule" },
      { label: "2.00¢ (British Airways / Cathay transfer bonus)", value: "2", description: "Transfer promo redemption" },
    ],
    values: {
      nickname: "RBC Avion Visa Infinite",
      issuer: "RBC",
      network: "VISA",
      lastFour: "",
      country: "CA",
      currency: "CAD",
      limit: "",
      statementDay: "",
      dueDay: "",
      aprPct: "20.99",
      annualFee: "120.00",
      feeMonthDay: "",
      feeCancelGraceDays: "30",
      rewards: {
        pointValueCents: "1.5",
        fxFeePct: "2.5",
        baseMultiplier: "1",
        capGroups: [],
        categoryRates: [
          { category: "travel", multiplier: "1.25", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
          { category: "hotel", multiplier: "1.25", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
        ],
        credits: [],
        conditions: [
          {
            id: "rbc-vip-waiver",
            label: "RBC Signature No Limit / VIP Banking active (fee rebate)",
            enabled: false,
            annualFeeReduction: "120.00",
          },
        ],
        merchantRates: [
          { id: "petro-points-extra", merchant: "Petro-Canada (linked RBC card: save 3¢/L + 20% extra points)", multiplier: "1.2", requiresConditionId: "" },
        ],
        baseRateOverrides: [],
      },
    },
  },
  {
    id: "rbc-ion-plus-visa",
    name: "RBC ION+ Visa",
    issuer: "RBC",
    network: "VISA",
    annualFee: 48,
    theme: "rbc-blue",
    programName: "RBC Avion Rewards",
    highlights: ["3x Groceries, Dining, Gas, Streaming, Transit", "1x Base on everything else", "Affordable $4/month fee ($48/yr)"],
    pointValuationOptions: [
      { label: "0.70¢ (Avion Premium / Gift Cards)", value: "0.7", description: "Direct redemption or transfer to Avion Elite" },
      { label: "1.00¢ (Avion transfer boost)", value: "1", description: "When merged with RBC Avion Visa Infinite" },
    ],
    values: {
      nickname: "RBC ION+ Visa",
      issuer: "RBC",
      network: "VISA",
      lastFour: "",
      country: "CA",
      currency: "CAD",
      limit: "",
      statementDay: "",
      dueDay: "",
      aprPct: "20.99",
      annualFee: "48.00",
      feeMonthDay: "",
      feeCancelGraceDays: "30",
      rewards: {
        pointValueCents: "0.7",
        fxFeePct: "2.5",
        baseMultiplier: "1",
        capGroups: [],
        categoryRates: [
          { category: "groceries", multiplier: "3", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
          { category: "dining", multiplier: "3", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
          { category: "gas", multiplier: "3", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
          { category: "streaming", multiplier: "3", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
          { category: "bills", multiplier: "3", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
        ],
        credits: [],
        conditions: [
          {
            id: "rbc-student-rebate",
            label: "RBC Advantage Banking for Students active (fee rebate)",
            enabled: false,
            annualFeeReduction: "48.00",
          },
        ],
        merchantRates: [
          { id: "ion-petro-canada", merchant: "Petro-Canada (Save 3¢/L + 20% Avion points)", multiplier: "1.2", requiresConditionId: "" },
        ],
        baseRateOverrides: [],
      },
    },
  },
  {
    id: "westjet-rbc-we",
    name: "WestJet RBC World Elite Mastercard",
    issuer: "RBC",
    network: "MASTERCARD",
    annualFee: 139,
    theme: "westjet",
    programName: "WestJet Dollars",
    highlights: ["2% on WestJet flights & vacations", "1.5% Base on everything", "Annual World Elite Companion Voucher", "Free First Checked Bag on WestJet"],
    pointValuationOptions: [{ label: "1.00¢ (WestJet Dollar = $1.00 CAD)", value: "1", description: "Direct CAD flight credit on WestJet" }],
    values: {
      nickname: "WestJet RBC World Elite",
      issuer: "RBC",
      network: "MASTERCARD",
      lastFour: "",
      country: "CA",
      currency: "CAD",
      limit: "",
      statementDay: "",
      dueDay: "",
      aprPct: "20.99",
      annualFee: "139.00",
      feeMonthDay: "",
      feeCancelGraceDays: "30",
      rewards: {
        pointValueCents: "1",
        fxFeePct: "2.5",
        baseMultiplier: "1.5",
        capGroups: [],
        categoryRates: [
          { category: "travel", multiplier: "2", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
          { category: "groceries", multiplier: "1.5", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
          { category: "gas", multiplier: "1.5", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
        ],
        credits: [],
        conditions: [],
        merchantRates: [
          { id: "westjet-direct-booking", merchant: "WestJet Airlines & Vacations", multiplier: "2", requiresConditionId: "" },
        ],
        baseRateOverrides: [],
      },
    },
  },

  // --- CIBC ---
  {
    id: "cibc-dividend-vi",
    name: "CIBC Dividend Visa Infinite Card",
    issuer: "CIBC",
    network: "VISA",
    annualFee: 120,
    theme: "cibc-maroon",
    programName: "Cashback",
    highlights: ["4% Groceries & Gas", "2% Dining, Transit & Recurring Bills", "1% Base", "$20k Category Cap"],
    pointValuationOptions: [{ label: "1.00¢ (Cashback)", value: "1", description: "Direct CAD cashback" }],
    values: {
      nickname: "CIBC Dividend Visa Infinite",
      issuer: "CIBC",
      network: "VISA",
      lastFour: "",
      country: "CA",
      currency: "CAD",
      limit: "",
      statementDay: "",
      dueDay: "",
      aprPct: "20.99",
      annualFee: "120.00",
      feeMonthDay: "",
      feeCancelGraceDays: "30",
      rewards: {
        pointValueCents: "1",
        fxFeePct: "2.5",
        baseMultiplier: "1",
        capGroups: [
          {
            id: "cibc-dividend-cap",
            label: "4% / 2% Category Spend ($20,000/year)",
            cap: "20000",
            capWindow: "YEAR",
          },
        ],
        categoryRates: [
          { category: "groceries", multiplier: "4", cap: "", capWindow: "YEAR", capGroupId: "cibc-dividend-cap", requiresConditionId: "" },
          { category: "gas", multiplier: "4", cap: "", capWindow: "YEAR", capGroupId: "cibc-dividend-cap", requiresConditionId: "" },
          { category: "dining", multiplier: "2", cap: "", capWindow: "YEAR", capGroupId: "cibc-dividend-cap", requiresConditionId: "" },
          { category: "bills", multiplier: "2", cap: "", capWindow: "YEAR", capGroupId: "cibc-dividend-cap", requiresConditionId: "" },
        ],
        credits: [],
        conditions: [
          {
            id: "cibc-smart-plus-waiver",
            label: "CIBC Smart Plus Banking Account active (fee waiver)",
            enabled: false,
            annualFeeReduction: "120.00",
          },
        ],
        merchantRates: [],
        baseRateOverrides: [],
      },
    },
  },
  {
    id: "cibc-aventura-vi",
    name: "CIBC Aventura Visa Infinite Card",
    issuer: "CIBC",
    network: "VISA",
    annualFee: 139,
    theme: "cibc-maroon",
    programName: "CIBC Aventura",
    highlights: ["2x CIBC Rewards Centre Travel", "1.5x Groceries, Gas, Drugstore", "1x Base", "4 Free Airport Lounge Passes + NEXUS Rebate"],
    pointValuationOptions: [
      { label: "1.00¢ (Aventura Air Travel)", value: "1", description: "Direct travel / airline flight redemption" },
      { label: "1.25¢ (Flight chart maximum)", value: "1.25", description: "Fixed flight reward schedule" },
    ],
    values: {
      nickname: "CIBC Aventura Visa Infinite",
      issuer: "CIBC",
      network: "VISA",
      lastFour: "",
      country: "CA",
      currency: "CAD",
      limit: "",
      statementDay: "",
      dueDay: "",
      aprPct: "20.99",
      annualFee: "139.00",
      feeMonthDay: "",
      feeCancelGraceDays: "30",
      rewards: {
        pointValueCents: "1",
        fxFeePct: "2.5",
        baseMultiplier: "1",
        capGroups: [
          {
            id: "cibc-aventura-cap",
            label: "1.5x Accelerated spend ($80,000/year)",
            cap: "80000",
            capWindow: "YEAR",
          },
        ],
        categoryRates: [
          { category: "groceries", multiplier: "1.5", cap: "", capWindow: "YEAR", capGroupId: "cibc-aventura-cap", requiresConditionId: "" },
          { category: "gas", multiplier: "1.5", cap: "", capWindow: "YEAR", capGroupId: "cibc-aventura-cap", requiresConditionId: "" },
          { category: "travel", multiplier: "2", cap: "", capWindow: "YEAR", capGroupId: "", requiresConditionId: "" },
        ],
        credits: [],
        conditions: [
          {
            id: "cibc-aventura-smart-plus-waiver",
            label: "CIBC Smart Plus Banking Account active (fee waiver)",
            enabled: false,
            annualFeeReduction: "139.00",
          },
        ],
        merchantRates: [],
        baseRateOverrides: [],
      },
    },
  },
  {
    id: "cibc-aventura-visa",
    name: "CIBC Aventura Visa Card",
    issuer: "CIBC",
    network: "VISA",
    annualFee: 0,
    theme: "cibc-maroon",
    programName: "CIBC Aventura",
    highlights: ["1x Groceries, Gas, Drugstore & CIBC Travel", "0.5x Base on everything else", "$0 Annual Fee"],
    pointValuationOptions: [{ label: "1.00¢ (Aventura Travel)", value: "1", description: "Direct travel flight booking" }],
    values: {
      nickname: "CIBC Aventura No-Fee Visa",
      issuer: "CIBC",
      network: "VISA",
      lastFour: "",
      country: "CA",
      currency: "CAD",
      limit: "",
      statementDay: "",
      dueDay: "",
      aprPct: "20.99",
      annualFee: "0.00",
      feeMonthDay: "",
      feeCancelGraceDays: "30",
      rewards: {
        pointValueCents: "1",
        fxFeePct: "2.5",
        baseMultiplier: "0.5",
        capGroups: [],
        categoryRates: [
          { category: "groceries", multiplier: "1", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
          { category: "gas", multiplier: "1", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
          { category: "travel", multiplier: "1", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
        ],
        credits: [],
        conditions: [],
        merchantRates: [],
        baseRateOverrides: [],
      },
    },
  },

  // --- BMO BANK OF MONTREAL ---
  {
    id: "bmo-eclipse-vi",
    name: "BMO eclipse Visa Infinite Card",
    issuer: "BMO",
    network: "VISA",
    annualFee: 120,
    theme: "bmo-blue",
    programName: "BMO Rewards",
    highlights: ["5x Groceries, Dining, Gas & Transit ($50k annual cap)", "$50 Annual Lifestyle Credit", "10% Bonus points with authorized user"],
    pointValuationOptions: [
      { label: "0.67¢ (BMO Travel)", value: "0.67", description: "150 BMO points = $1.00 travel" },
      { label: "0.50¢ (Statement credit)", value: "0.50", description: "200 BMO points = $1.00 cash" },
    ],
    values: {
      nickname: "BMO eclipse Visa Infinite",
      issuer: "BMO",
      network: "VISA",
      lastFour: "",
      country: "CA",
      currency: "CAD",
      limit: "",
      statementDay: "",
      dueDay: "",
      aprPct: "20.99",
      annualFee: "120.00",
      feeMonthDay: "",
      feeCancelGraceDays: "30",
      rewards: {
        pointValueCents: "0.67",
        fxFeePct: "2.5",
        baseMultiplier: "1",
        capGroups: [
          {
            id: "bmo-eclipse-5x-cap",
            label: "5x Accelerated spend ($50,000/year)",
            cap: "50000",
            capWindow: "YEAR",
          },
        ],
        categoryRates: [
          { category: "groceries", multiplier: "5", cap: "", capWindow: "YEAR", capGroupId: "bmo-eclipse-5x-cap", requiresConditionId: "" },
          { category: "dining", multiplier: "5", cap: "", capWindow: "YEAR", capGroupId: "bmo-eclipse-5x-cap", requiresConditionId: "" },
          { category: "gas", multiplier: "5", cap: "", capWindow: "YEAR", capGroupId: "bmo-eclipse-5x-cap", requiresConditionId: "" },
          { category: "travel", multiplier: "5", cap: "", capWindow: "YEAR", capGroupId: "bmo-eclipse-5x-cap", requiresConditionId: "" },
        ],
        credits: [
          { id: "bmo-lifestyle-credit", label: "Annual lifestyle credit", value: "50.00", period: "YEAR" },
        ],
        conditions: [
          {
            id: "bmo-premium-waiver",
            label: "BMO Premium Plan banking active (fee waiver)",
            enabled: false,
            annualFeeReduction: "120.00",
          },
        ],
        merchantRates: [],
        baseRateOverrides: [],
      },
    },
  },
  {
    id: "bmo-ascend-we",
    name: "BMO Ascend World Elite Mastercard",
    issuer: "BMO",
    network: "MASTERCARD",
    annualFee: 150,
    theme: "bmo-blue",
    programName: "BMO Rewards",
    highlights: ["5x Travel ($15k/yr cap)", "3x Dining, Entertainment & Recurring Bills ($10k/yr cap)", "1x Base", "4 Free Airport Lounge Passes"],
    pointValuationOptions: [
      { label: "0.67¢ (BMO Travel)", value: "0.67", description: "150 BMO points = $1.00 travel" },
      { label: "0.50¢ (Statement credit)", value: "0.50", description: "200 BMO points = $1.00 cash" },
    ],
    values: {
      nickname: "BMO Ascend World Elite",
      issuer: "BMO",
      network: "MASTERCARD",
      lastFour: "",
      country: "CA",
      currency: "CAD",
      limit: "",
      statementDay: "",
      dueDay: "",
      aprPct: "20.99",
      annualFee: "150.00",
      feeMonthDay: "",
      feeCancelGraceDays: "30",
      rewards: {
        pointValueCents: "0.67",
        fxFeePct: "2.5",
        baseMultiplier: "1",
        capGroups: [],
        categoryRates: [
          { category: "travel", multiplier: "5", cap: "15000", capWindow: "YEAR", capGroupId: "", requiresConditionId: "" },
          { category: "dining", multiplier: "3", cap: "10000", capWindow: "YEAR", capGroupId: "", requiresConditionId: "" },
          { category: "bills", multiplier: "3", cap: "10000", capWindow: "YEAR", capGroupId: "", requiresConditionId: "" },
          { category: "streaming", multiplier: "3", cap: "10000", capWindow: "YEAR", capGroupId: "", requiresConditionId: "" },
        ],
        credits: [],
        conditions: [
          {
            id: "bmo-ascend-premium-waiver",
            label: "BMO Premium Plan banking active (fee waiver)",
            enabled: false,
            annualFeeReduction: "150.00",
          },
        ],
        merchantRates: [],
        baseRateOverrides: [],
      },
    },
  },

  // --- NATIONAL BANK ---
  {
    id: "national-bank-we",
    name: "National Bank World Elite Mastercard",
    issuer: "National Bank",
    network: "MASTERCARD",
    annualFee: 150,
    theme: "national-bank",
    programName: "NBC Rewards",
    highlights: ["5x Groceries & Dining (on first $2,500/mo)", "2x Gas, Transit & Recurring Bills", "Up to $150 Annual Travel Credit", "Unlimited Montreal National Bank Lounge"],
    pointValuationOptions: [
      { label: "1.00¢ (A La Carte Travel)", value: "1", description: "Direct travel / flight ticket booking" },
      { label: "0.83¢ (Statement credit)", value: "0.83", description: "Cash back statement credit" },
    ],
    values: {
      nickname: "National Bank World Elite",
      issuer: "National Bank",
      network: "MASTERCARD",
      lastFour: "",
      country: "CA",
      currency: "CAD",
      limit: "",
      statementDay: "",
      dueDay: "",
      aprPct: "20.99",
      annualFee: "150.00",
      feeMonthDay: "",
      feeCancelGraceDays: "30",
      rewards: {
        pointValueCents: "1",
        fxFeePct: "2.5",
        baseMultiplier: "1",
        capGroups: [
          {
            id: "nbc-we-food-cap",
            label: "5x Groceries & Dining ($2,500/month)",
            cap: "2500",
            capWindow: "MONTH",
          },
        ],
        categoryRates: [
          { category: "groceries", multiplier: "5", cap: "", capWindow: "MONTH", capGroupId: "nbc-we-food-cap", requiresConditionId: "" },
          { category: "dining", multiplier: "5", cap: "", capWindow: "MONTH", capGroupId: "nbc-we-food-cap", requiresConditionId: "" },
          { category: "gas", multiplier: "2", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
          { category: "bills", multiplier: "2", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
          { category: "travel", multiplier: "2", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
        ],
        credits: [
          { id: "nbc-travel-credit", label: "Annual travel enhancement credit (airport parking, baggage, seat selection)", value: "150.00", period: "YEAR" },
        ],
        conditions: [],
        merchantRates: [],
        baseRateOverrides: [],
      },
    },
  },

  // --- MBNA / ROGERS / TANGERINE / CANADIAN TIRE / WEALTHSIMPLE / PC / AMAZON / CRYPTO ---
  {
    id: "mbna-rewards-we",
    name: "MBNA Rewards World Elite Mastercard",
    issuer: "MBNA",
    network: "MASTERCARD",
    annualFee: 120,
    theme: "mbna",
    programName: "MBNA Rewards",
    highlights: ["5x Dining, Groceries, Digital Media & Utilities ($50k annual cap each)", "1x Base", "Birthday Bonus 10%"],
    pointValuationOptions: [
      { label: "1.00¢ (Travel booking / e-Gift cards)", value: "1", description: "Direct travel or select merchandise" },
      { label: "0.83¢ (Cash back statement credit)", value: "0.83", description: "Cash back statement credit redemption" },
    ],
    values: {
      nickname: "MBNA Rewards World Elite",
      issuer: "MBNA",
      network: "MASTERCARD",
      lastFour: "",
      country: "CA",
      currency: "CAD",
      limit: "",
      statementDay: "",
      dueDay: "",
      aprPct: "20.99",
      annualFee: "120.00",
      feeMonthDay: "",
      feeCancelGraceDays: "30",
      rewards: {
        pointValueCents: "1",
        fxFeePct: "2.5",
        baseMultiplier: "1",
        capGroups: [],
        categoryRates: [
          { category: "dining", multiplier: "5", cap: "50000", capWindow: "YEAR", capGroupId: "", requiresConditionId: "" },
          { category: "groceries", multiplier: "5", cap: "50000", capWindow: "YEAR", capGroupId: "", requiresConditionId: "" },
          { category: "streaming", multiplier: "5", cap: "50000", capWindow: "YEAR", capGroupId: "", requiresConditionId: "" },
          { category: "bills", multiplier: "5", cap: "50000", capWindow: "YEAR", capGroupId: "", requiresConditionId: "" },
        ],
        credits: [],
        conditions: [],
        merchantRates: [],
        baseRateOverrides: [],
      },
    },
  },
  {
    id: "amazon-rewards-mc",
    name: "Amazon.ca Rewards Mastercard",
    issuer: "MBNA",
    network: "MASTERCARD",
    annualFee: 0,
    theme: "amazon",
    programName: "Amazon Rewards",
    highlights: ["2.5% Amazon.ca & Whole Foods (with Prime)", "1.5% (without Prime)", "1% Base", "$0 Annual Fee"],
    pointValuationOptions: [{ label: "1.00¢ (Amazon CAD statement credit)", value: "1", description: "100 pts = $1.00 Amazon.ca gift card" }],
    values: {
      nickname: "Amazon.ca Rewards Mastercard",
      issuer: "MBNA",
      network: "MASTERCARD",
      lastFour: "",
      country: "CA",
      currency: "CAD",
      limit: "",
      statementDay: "",
      dueDay: "",
      aprPct: "19.99",
      annualFee: "0.00",
      feeMonthDay: "",
      feeCancelGraceDays: "30",
      rewards: {
        pointValueCents: "1",
        fxFeePct: "2.5",
        baseMultiplier: "1",
        capGroups: [],
        categoryRates: [
          { category: "groceries", multiplier: "1", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
        ],
        credits: [],
        conditions: [
          {
            id: "amazon-prime-active",
            label: "Active Amazon Prime membership (enables 2.5% at Amazon & Whole Foods)",
            enabled: true,
            annualFeeReduction: "",
          },
        ],
        merchantRates: [
          { id: "amazon-ca-prime-rate", merchant: "Amazon.ca & Whole Foods Market", multiplier: "2.5", requiresConditionId: "amazon-prime-active" },
        ],
        baseRateOverrides: [],
      },
    },
  },
  {
    id: "pc-insiders-we",
    name: "PC Insiders World Elite Mastercard",
    issuer: "President's Choice Bank",
    network: "MASTERCARD",
    annualFee: 120,
    theme: "pc-optimum",
    programName: "PC Optimum",
    highlights: ["40 pts/$ (4%) at Loblaw grocery stores", "35 pts/$ (3.5%) at Shoppers Drug Mart", "10 pts/$ (1%) Base", "PC Express Pass Included"],
    pointValuationOptions: [{ label: "1.00¢ (10 pts = 1¢ at Loblaw / Shoppers)", value: "0.1", description: "10,000 PC Optimum pts = $10.00" }],
    values: {
      nickname: "PC Insiders World Elite",
      issuer: "President's Choice Bank",
      network: "MASTERCARD",
      lastFour: "",
      country: "CA",
      currency: "CAD",
      limit: "",
      statementDay: "",
      dueDay: "",
      aprPct: "20.99",
      annualFee: "120.00",
      feeMonthDay: "",
      feeCancelGraceDays: "30",
      rewards: {
        pointValueCents: "1",
        fxFeePct: "2.5",
        baseMultiplier: "1",
        capGroups: [],
        categoryRates: [
          { category: "groceries", multiplier: "4", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
        ],
        credits: [],
        conditions: [],
        merchantRates: [
          { id: "pc-shoppers-35x", merchant: "Shoppers Drug Mart & Pharmaprix", multiplier: "3.5", requiresConditionId: "" },
          { id: "pc-joe-fresh-40x", merchant: "Joe Fresh", multiplier: "4", requiresConditionId: "" },
        ],
        baseRateOverrides: [],
      },
    },
  },
  {
    id: "rogers-red-we",
    name: "Rogers Red World Elite Mastercard",
    issuer: "Rogers Bank",
    network: "MASTERCARD",
    annualFee: 0,
    theme: "rogers-red",
    programName: "Cashback",
    highlights: ["2% Unlimited with Rogers/Fido/Shaw service (1.5% base)", "3% on USD purchases", "$0 Annual Fee", "1.5x Redemption boost on Rogers bills"],
    pointValuationOptions: [{ label: "1.00¢ (Cashback)", value: "1", description: "Direct CAD cash back" }],
    values: {
      nickname: "Rogers Red World Elite",
      issuer: "Rogers Bank",
      network: "MASTERCARD",
      lastFour: "",
      country: "CA",
      currency: "CAD",
      limit: "",
      statementDay: "",
      dueDay: "",
      aprPct: "19.99",
      annualFee: "0.00",
      feeMonthDay: "",
      feeCancelGraceDays: "30",
      rewards: {
        pointValueCents: "1",
        fxFeePct: "2.5",
        baseMultiplier: "1.5",
        capGroups: [],
        categoryRates: [
          { category: "online_foreign", multiplier: "3", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
        ],
        credits: [],
        conditions: [
          {
            id: "rogers-service-linked",
            label: "Eligible Rogers, Fido, Shaw, or Comwave service linked (2% all-spend)",
            enabled: true,
            annualFeeReduction: "",
          },
        ],
        merchantRates: [],
        baseRateOverrides: [
          {
            id: "rogers-all-spend-2pct",
            label: "2% All-spend with Rogers service",
            multiplier: "2",
            requiresConditionId: "rogers-service-linked",
            cap: "61000",
            capWindow: "YEAR",
          },
        ],
      },
    },
  },
  {
    id: "tangerine-moneyback",
    name: "Tangerine Money-Back World Mastercard",
    issuer: "Tangerine",
    network: "MASTERCARD",
    annualFee: 0,
    theme: "tangerine-orange",
    programName: "Cashback",
    highlights: ["2% Unlimited on 2–3 Chosen Categories", "0.5% Base", "$0 Annual Fee", "Monthly Payout"],
    pointValuationOptions: [{ label: "1.00¢ (Cashback)", value: "1", description: "Monthly cash deposit" }],
    values: {
      nickname: "Tangerine Money-Back",
      issuer: "Tangerine",
      network: "MASTERCARD",
      lastFour: "",
      country: "CA",
      currency: "CAD",
      limit: "",
      statementDay: "",
      dueDay: "",
      aprPct: "19.95",
      annualFee: "0.00",
      feeMonthDay: "",
      feeCancelGraceDays: "30",
      rewards: {
        pointValueCents: "1",
        fxFeePct: "2.5",
        baseMultiplier: "0.5",
        capGroups: [],
        categoryRates: [
          { category: "groceries", multiplier: "2", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
          { category: "bills", multiplier: "2", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "" },
          { category: "gas", multiplier: "2", cap: "", capWindow: "MONTH", capGroupId: "", requiresConditionId: "tangerine-savings-account" },
        ],
        credits: [],
        conditions: [
          {
            id: "tangerine-savings-account",
            label: "Rewards deposited into Tangerine Savings Account (unlocks 3rd 2% category)",
            enabled: true,
            annualFeeReduction: "",
          },
        ],
        merchantRates: [],
        baseRateOverrides: [],
      },
    },
  },
  {
    id: "triangle-we",
    name: "Triangle World Elite Mastercard",
    issuer: "Canadian Tire Bank",
    network: "MASTERCARD",
    annualFee: 0,
    theme: "triangle-red",
    programName: "CT Money",
    highlights: ["4% at Canadian Tire, Sport Chek, Mark's", "3% Groceries ($12k/yr cap)", "Free Roadside Assistance Gold Plan", "No Annual Fee"],
    pointValuationOptions: [{ label: "1.00¢ (CT Money)", value: "1", description: "CT$1.00 = C$1.00 at Canadian Tire family of stores" }],
    values: {
      nickname: "Triangle World Elite",
      issuer: "Canadian Tire Bank",
      network: "MASTERCARD",
      lastFour: "",
      country: "CA",
      currency: "CAD",
      limit: "",
      statementDay: "",
      dueDay: "",
      aprPct: "20.99",
      annualFee: "0.00",
      feeMonthDay: "",
      feeCancelGraceDays: "30",
      rewards: {
        pointValueCents: "1",
        fxFeePct: "2.5",
        baseMultiplier: "1",
        capGroups: [],
        categoryRates: [
          { category: "groceries", multiplier: "3", cap: "12000", capWindow: "YEAR", capGroupId: "", requiresConditionId: "" },
        ],
        credits: [],
        conditions: [],
        merchantRates: [
          { id: "ct-family-stores", merchant: "Canadian Tire, Sport Chek, Mark's, Party City, Atmosphere", multiplier: "4", requiresConditionId: "" },
        ],
        baseRateOverrides: [],
      },
    },
  },
  {
    id: "wealthsimple-vip",
    name: "Wealthsimple Visa Infinite Privilege",
    issuer: "Wealthsimple",
    network: "VISA",
    annualFee: 240,
    theme: "wealthsimple-black",
    programName: "Cashback",
    highlights: ["2% Unlimited Cash Back on Everything", "0% FX Fee (No Foreign Currency Fees)", "Fee Waived with $100k+ assets or direct deposit", "DragonPass Lounge Visits"],
    pointValuationOptions: [{ label: "1.00¢ (Cashback)", value: "1", description: "Deposited to Wealthsimple cash/invest account" }],
    values: {
      nickname: "Wealthsimple VIP Card",
      issuer: "Wealthsimple",
      network: "VISA",
      lastFour: "",
      country: "CA",
      currency: "CAD",
      limit: "",
      statementDay: "",
      dueDay: "",
      aprPct: "20.99",
      annualFee: "240.00",
      feeMonthDay: "",
      feeCancelGraceDays: "30",
      rewards: {
        pointValueCents: "1",
        fxFeePct: "0",
        baseMultiplier: "2",
        capGroups: [],
        categoryRates: [],
        credits: [],
        conditions: [
          {
            id: "ws-vip-waiver",
            label: "$100k+ qualifying Wealthsimple assets or $4,000/mo direct deposit (fee waived)",
            enabled: true,
            annualFeeReduction: "240.00",
          },
        ],
        merchantRates: [],
        baseRateOverrides: [],
      },
    },
  },
  {
    id: "crypto-indigo",
    name: "Crypto.com Prepaid Visa Card (Royal Indigo)",
    issuer: "Crypto.com",
    network: "VISA",
    annualFee: 0,
    theme: "crypto-indigo",
    programName: "CRO Rewards",
    highlights: ["3% CRO Rewards (with Level Up / lockup)", "0% FX Fee", "100% Spotify & Netflix rebates", "Airport LoungeKey Access"],
    pointValuationOptions: [{ label: "1.00¢ (CRO Token Equivalent)", value: "1", description: "Direct CRO cashback value" }],
    values: {
      nickname: "Crypto.com Visa Royal Indigo",
      issuer: "Crypto.com",
      network: "VISA",
      lastFour: "",
      country: "CA",
      currency: "CAD",
      limit: "",
      statementDay: "",
      dueDay: "",
      aprPct: "0",
      annualFee: "0.00",
      feeMonthDay: "",
      feeCancelGraceDays: "30",
      rewards: {
        pointValueCents: "1",
        fxFeePct: "0",
        baseMultiplier: "0",
        capGroups: [],
        categoryRates: [],
        credits: [
          { id: "crypto-spotify-rebate", label: "Monthly Spotify rebate (up to $14.99/mo)", value: "14.99", period: "MONTH" },
          { id: "crypto-netflix-rebate", label: "Monthly Netflix rebate (up to $14.99/mo)", value: "14.99", period: "MONTH" },
        ],
        conditions: [
          {
            id: "crypto-pro-lockup",
            label: "Level Up Pro subscription or CRO lockup active (enables 3% rewards)",
            enabled: true,
            annualFeeReduction: "",
          },
        ],
        merchantRates: [],
        baseRateOverrides: [
          {
            id: "crypto-pro-3pct",
            label: "3% CRO Rewards",
            multiplier: "3",
            requiresConditionId: "crypto-pro-lockup",
            cap: "2500",
            capWindow: "MONTH",
          },
        ],
      },
    },
  },
];

export const CATEGORY_ICONS: Record<SpendCategory, string> = {
  groceries: "🛒",
  dining: "🍽️",
  gas: "⛽",
  bills: "⚡",
  streaming: "📺",
  travel: "✈️",
  warehouse: "🏬",
  home_improvement: "🔨",
  hotel: "🏨",
  online_foreign: "🌐",
  everything_else: "💳",
};
