import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";

// The whole milestone exists to shrink this. A test, not a hope.
const BUDGET_CHARS = 2400; // ~600 tokens at 4 chars/token

function ourContent(path: string): string {
  const text = readFileSync(path, "utf8");
  // The Next.js block is regenerated by `next dev` and is not ours to shrink.
  return text.replace(
    /<!-- BEGIN:nextjs-agent-rules -->[\s\S]*?<!-- END:nextjs-agent-rules -->/g,
    "",
  );
}

describe("always-loaded agent context", () => {
  it("keeps AGENTS.md within 40 lines of our own content", () => {
    const lines = ourContent("AGENTS.md")
      .split("\n")
      .filter((l) => l.trim().length > 0);
    expect(lines.length).toBeLessThanOrEqual(40);
  });

  it("keeps the combined always-loaded budget under 2400 characters", () => {
    const total = ourContent("AGENTS.md").length + ourContent("CLAUDE.md").length;
    expect(total).toBeLessThanOrEqual(BUDGET_CHARS);
  });

  it("never @-imports ECOSYSTEM.md, which would load it eagerly on every turn", () => {
    const combined = readFileSync("AGENTS.md", "utf8") + readFileSync("CLAUDE.md", "utf8");
    expect(combined).not.toMatch(/^@ECOSYSTEM\.md/m);
  });

  it("reaches each demoted policy by a markdown link", () => {
    const text = readFileSync("AGENTS.md", "utf8");
    for (const target of [
      "REPO_MAP.md",
      "docs/policies/card-ownership.md",
      "docs/policies/marketlens.md",
      "docs/runbooks/quote-cache.md",
      "docs/policies/exceptions.json",
    ]) {
      expect(text).toContain(`(${target})`);
    }
  });

  it("keeps the Next.js block that `next dev` regenerates", () => {
    // Our content lives outside the markers precisely so regeneration is a no-op
    // on it. Dropping the block re-creates it as an uncommitted change forever.
    const text = readFileSync("AGENTS.md", "utf8");
    expect(text).toContain("<!-- BEGIN:nextjs-agent-rules -->");
    expect(text).toContain("<!-- END:nextjs-agent-rules -->");
  });
});
